sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy

matrix:
  allow_failures:
    # Till https://travis-ci.org/circuits/circuits/jobs/192188096 is solved.
    - python: pypy
    # Till https://travis-ci.org/circuits/circuits/jobs/192669838 is solved.
    - os: osx
  include:
    - python: 2.7
      os: osx
      language: generic
      env: TOXENV=py27
    - python: 3.6
      os: osx
      language: generic
      env: TOXENV=py36
      before_install: brew install python3
    - python: pypy
      os: osx
      language: generic
      env: TOXENV=pypy
      before_install: brew install pypy
    - python: 3.6
      script: flake8
    - python: 3.6
      script: isort -c --diff

install:
  - pip install tox-travis
  - pip install -Ur requirements-test.txt
  - pip install -Ue .

script: tox

after_success: coveralls

notifications:
  irc: "chat.freenode.net#circuits"
